### ISSUE TITLE
[Question] Reason for using Glimpse over upstream project for average user

### ISSUE THREAD

**Issue by pipboy96** [glimpse-editor/Glimpse#116]
While I agree that upstream project's name may be problematic for some users, is there any reason (right now or in the future) for average home/private users (assuming they are okay with the upstream project's name) to stick with this fork over the upstream?

**Comment by BrainBlasted** [comment]
Currently the main reason is the naming scheme. In the future we plan to overhaul the UI to be more useable.

**Comment by RayoGundead** [comment]
if proper CMYK support and a real Circle tool happen then you will see a migration happen in real time.

**Comment by botfap** [comment]
No reason whatsoever for the vast majority of people. The average user doesn't care about the name, they care about functionality, ease of use, ease of availability, etc

A small bunch of over sensitive kids starting an emotional tantrum driven fork isnt going to get much traction outside of the ever shrinking social justice cult

**Comment by pipboy96** [comment]
@botfap well, for now you are right that most people have no reason to choose this fork, but please don't troll.

**Comment by botfap** [comment]
Absolutely no trolling involved, thats a strange assertion to make...

GIMP is used widely across all sorts of businesses and educational settings and has been for over a decade. I have seen it used in schools, colleges and universities. I have see it used and deployed it in businesses from 25 staff to 250,000 staff. I have personally seen it deployed in Germany, United Kingdom, France, Italy, Spain, Belgium, Austria, Switzerland, Iran, Canada, United States, Australia, India and Ecuador. I have heard many, many people giggle over the name but never had or even heard of a single complaint from an actual user

If you are working in a business or educational establishment where the acronymic name of an image editor prevents you from using that software, then the name of the software is not the problem, the establishment you chose to spend your time at is the problem. If you personally feel that you cant use a piece of software because of its name, thats perfectly OK, its your choice, but you should recognise that you are in a minority and most people are not as sensitive as you

This project is trying to fix symptoms, not causes, thats why it wont succeed. Im all for the betterment of software, especially software as important as GIMP. UI fixes for GIMP are a genuine problem and anyone trying to help that should be applauded. That isnt whats happening here. There are already many, many other GIMP forks created to deal with UI issues. If this effort went to contributing to one of those projects instead then it would have my support, instead its virtue signalling nonsense designed to feed the ego's of a very small group of people who cant deal with the fact that most other people dont think in the same way as they do

**Comment by TrechNex** [comment]
@botfap you are welcome to your opinion. However, the evidence you have supplied here is entirely anecdotal and related to your own experience, which is not universal.

Bryan Lunduke recently ran a poll of his own followers asking if this fork was worthwhile. 1 in 5 people on Twitter and 1 in 4 on Mastodon said it was a good idea. So while we are in the minority, it is not as small as you may think. In addition this project has 500 followers on Mastodon, 100 on Twitter, $88 a month pledged on Patreon and 50+ people on our project Matrix channel before we have even pushed out a binary release. Clearly there are people out there who see a need for this fork to exist.

Regardless of our motivations, we would still have had to release 0.1 as just a cosmetic rebrand with a new name and improved build tools. If you also look over the Issues for this Github project, you will see there is *much more* planned for future releases than just a rename. Although it is fair to say that is the thing causing the most controversy!

Finally, changing the name is not the only reason for the fork. This is a piece of software many of us have used for some time and we want to attract new ideas, contributors and resources towards a free software project that deserves it. The project has donate links for upstream sprinkled through our own documentation and website, and we are already looking to donate 10% of all the money receive through Patreon to GNU Image Manipulation Program regardless of our own needs and costs.

So my suggestion is that before you dismiss or judge this project as the product of "left-leaning social justice warriors" with nothing new to contribute, you may want to examine whether perhaps there is more to this project than meets the eye. :)
