### ISSUE TITLE
Recover dialog still mentions the GNU IMP

### ISSUE THREAD

**Issue by bochecha** [glimpse-editor/Glimpse#190]
I just got this this morning.

![Screenshot from 2019-10-24 11-06-02](https://user-images.githubusercontent.com/272170/67470806-a8b7a380-f64e-11e9-80a1-00d70e00dc94.png)

We probably want to fix it before 0.1?

**Comment by igalic** [comment]
and it uses a Wilber icon, too…

**Comment by Member1221** [comment]
There's still a lot of places that still have remnants of upstream's stuff. It'll take a lot of time to remove.

**Comment by lorendias** [comment]
Is it not possible to do a $sed find/replace or simply open the project folder in Sublime/Notepad++ and do a complete find of all instances of "GIMP", "G.I.M.P." and "GNU Image" to identify all remaining instances?

**Comment by Member1221** [comment]
For now we still need to keep upstream's plugins compatible, therefore find and replace is not that useful; doing such could change symbols such that plugins would stop working, etc.

**Comment by TrechNex** [comment]
Indeed, this is not the first time someone has made that suggestion to us.

There is *some* benefit to using find and replace, but only in a very limited way with some of the translation files. Typically there are hard coded values in XML files or the code itself that are dynamically swapped with values from the translation files at runtime, so anything we change in the translation files also has to be hunted down in the code and manually changed. So... limited usefulness.

We also can't just run a find and replace on the build system because it will break in ways that are ridiculously time-consuming to troubleshoot. Code refactoring also breaks the subcomponents and plug-in API, which is a particular problem because core functions have been pushed out to subcomponents and plug-ins, so if they don't work the entire application doesn't work.

The build system is also a massive can of worms that we do our best not to tangle with. We literally maintain a blank README file at the root of the code because attempting to remove it stops subcomponents and certain plug-ins from building properly.

So whenever I see people saying "Why don't you just use find and replace?" as though this is a thing we haven't thought of or had suggested to us by dozens of people, it tends to illicit and eyeroll followed by a weary sigh from me. :sweat_smile:

**Comment by TrechNex** [comment]
As an addendum to that, the fix for this issue was literally to hunt down the hard coded value in the code because I had already fixed the translation files. So I guess that's further evidence that find and replace has limited usefulness, as I missed that change _because_ I was using an automated tool.

**Comment by TrechNex** [comment]
Closing as fixed
