### ISSUE TITLE
On Windows, Glimpse 0.1 BETA and GNU Image Manipulation Program 2.10.12 cannot run at the same time

### ISSUE THREAD

**Issue by TrechNex** [glimpse-editor/Glimpse#196]
Both applications can be installed at the same time, and they do not read from or interfere with each others' configuration files.

However if you attempt to launch Glimpse when GNU Image Manipulation Program is already launched (or vice versa) it will fail silently because it assumes you are trying to launch a second instance of the same program.

This could either be fixed for 0.1 or filed as a "known issue" for now.

**Comment by bochecha** [comment]
Modern Gtk3 apps use [GtkApplication]() which has a builtin way to handle unicity: that is, a "unique" app can only have a single instance at a given time, trying to run it again will just focus the already running window.

Before GtkApplication, apps used [libunique]() which was the inspiraton for GtkApplication.

But the GNU IMP is even older, so it has its own code to handle unicity: https://github.com/glimpse-editor/Glimpse/blob/dev-g210/app/unique.c

On Linux, this works with DBus: the app takes a name on the bus on startup, and if it finds that name is already taken then it just raises the window which took that name.

This works properly on Linux because I changed the DBus name taken by Glimpse: https://github.com/glimpse-editor/Glimpse/blob/10accb8603720aa4d6a27d4c9ce5f5d193bd74eb/app/gui/gimpdbusservice.h#L31

On Windows there is no DBus though, so it works differently: https://github.com/glimpse-editor/Glimpse/blob/dev-g210/app/unique.c#L165-L230

Looking at this code, it seems what needs to be changed is these values: https://github.com/glimpse-editor/Glimpse/blob/9cdeded22675d02cd1d536b2a0aff4448d15885c/app/gui/gui-unique.h#L22-L23

I won't make a pull request because I don't have a Windows machine to test it, but I think that's all it would take.

If possible, I recommend using values similar to the app id on Linux. Maybe something like the following?

```c
#define GIMP_UNIQUE_WIN32_WINDOW_CLASS  L"org.glimpse_editor.Glimpse"
#define GIMP_UNIQUE_WIN32_WINDOW_NAME   L"org.glimpse_editor.Glimpse.Window"
```

The advantage of using the same app id is that if we need to change it, a simple `grep` will find all occurences. Or rather, if upstream had used that convention, I'd have found this and changed it at the same time I did the original app id work in #142. :disappointed:

**Comment by TrechNex** [comment]
No worries. I think I will probably end up fixing it this evening as I'm having to do Windows things atm. Plus I can use a Linux VM to check things work properly on the Linux side.

Thank you for this detail. That will have saved me *hours* of work!

**Comment by Member1221** [comment]
Also adding the note that to make Gtk3 (and 4) applications be non-unique you just have to set the GApplication flag to NON_UNIQUE

Example (in D)
```d
import std.stdio;
import gtk.Application;
import app.window;

int main(string[] args)
{
    scope(failure) {
        // TODO: If a crash happens, make an autosave.
    }

    Application app = new Application("dk.cospec.wsedit", GApplicationFlags.NON_UNIQUE);
    app.addOnActivate((appx) { new AppWindow(app); });
    return app.run(args);
}
```

**Comment by TrechNex** [comment]
Success! 
![side-by-side](https://user-images.githubusercontent.com/45732696/68068789-00da5e00-fd51-11e9-846c-82110c3b3953.png)
