### ISSUE TITLE
Please add a ppa or *.deb package?

### ISSUE THREAD

**Issue by PJSingh5000** [glimpse-editor/Glimpse#236]
Firstly, congratulations on your 1st release!

Secondly, please add a PPA or provide *.deb packages for those of us who do not use snap or flatpack.

(PPA preferred so we can get updates easily).

**Comment by TrechNex** [comment]
The current project policy is that we do not package Glimpse for specific distributions (i.e. those that use DEB, RPM, pacman, etc) as they are far more expert than we could possibly hope to be at that task.

If someone decides to maintain a PPA that packages our free software as a DEB then we will accept any code changes they need to facilitate that. We already do this for a community-supported Snap that can be installed through the Ubuntu Software Centre.

This is for the practical reason that we do not have the resources to maintain an ever-expanding number of packaging formats used within the Linux ecosystem. :D

I have not closed this issue or marked it as "Won't Fix" because I would like this issue to be discussed in our Matrix channels to determine if this is something the communirt and project would like to do.

**Comment by chaomodus** [comment]
I shan't be exactly volunteering for this but I can definitely help facilitate and participate if somebody steps up to volunteer for this.

**Comment by TrechNex** [comment]
Linking to #242 

In practise I don't think we will ever directly support packaging as DEB or hosting a PPA. But if someone from the wider community wants to do this we will support them and merge changes to help them.

**Comment by TrechNex** [comment]
After 0.2.0 is released I intend to spend some time experimenting with builds on the Open Build Service so we can resolve any lingering problems that distro maintainers and BSD ports team would encounter with our application.

**Comment by PJSingh5000** [comment]
I appreciate this! I hope someone is willing to eventually package and host as PPA.

**Comment by TrechNex** [comment]
This has been moved to #468.

We have determined that we do not have the capacity or resources to maintain our own DEB packaging or PPA, and any such work would depend on us fixing conflicts with the DEB packages for the GNU Image Manipulation Program.

Our plan is to document how to package as a DEB once the conflicts have been resolved so that the wider Linux community can pick up this task.

**Comment by PJSingh5000** [comment]
Thank you for looking into this.
Perhaps in the future it will be feasible.
I look forward to reading the documentation.
