### ISSUE TITLE
the goal of this project

### ISSUE THREAD

**Issue by fikrillah** [glimpse-editor/Glimpse#241]
hi, i would like to give share opinion about this project's goal. hope it could help in any way, or at least make some meaningful conversation about his project.

i'm sorry if i sound bossy, probably some of the point is already being done, but i need this to get things out of my chest, and i'm hopping many feedback, so this is my take about this project goal:

**1. Set the clear goals of the project**
make detailed roadmap of the project. when one work due, set the focus of the project time to time,   make a good project management, decide who's working what, and be committed to that. make sure the development of glimpse is going efficiently, both the amount of work and the time. make the patrons money really worthy. 

**2. get in touch with gimp devs**
besides contributing upstream, glimpse devs should be in touch with gimp devs, make sure there's no same work that being work on both project. make some kind of unofficial agreement about the focus of the project, for example, gimp devs should be focusing on underlying technology, while glimpse devs should be studying and implementing best UI/UX for comfy and efficient workflow for the user

**3. forking form recent code of gimp, instead of stable release**
if we base our project from stable release, our project will be obsolete soon, it's more work for glimse devs when major version of gimp is released. just imagine the pile of task to do when version 3 of gimp is released. it's using many different stuff, and it makes glimpse devs should redo many task that just won't work on new version. probably just base the project from master, or with many bleeding edge branches

also with stable release of gimp as the base, glimpse devs will not be exposed to the problem that gimp devs are struggling. it's necessary to understand the problems, because it could trigger may ideas and innovation, especially the one that compatible with glimpse goal and not with gimp's for whatever reason.

 for example, things that cannot be change because it's too much work for gimp, or things that already decided but it's not the best implementation for UX. things like non-standard shortcut, or how complicated it is to set custom brush on gimp. 

glimpse as new project has better chance to change that compared to gimp that could't just change things because it already has users that are used to it's default workflow (that some of it is inefficient or unpleasant experience)

**Comment by TrechNex** [comment]
Thank you for your suggestions on this. I'll take these suggestions one by one, and I hope it answers some of your questions. (You might also be interested in reading the FAQs here: https://glimpse-editor.org/about/)

> 1. Set the clear goals of the project
make detailed roadmap of the project. when one work due, set the focus of the project time to time, make a good project management, decide who's working what, and be committed to that. make sure the development of glimpse is going efficiently, both the amount of work and the time. make the patrons money really worthy.

The main issue here is that we are a free software project, so we are reliant on volunteer labour from people interested usually in one very specific thing. People might also promise to do things but run into blockers they cannot resolve, or unrelated "life" things may happen to them that prevent them from delivering what they promised.

For this reason what we do is create milestones with "candidate" issues we discuss on Matrix, then we create a fixed version milestone that will pull issues into or drop them out of depending on our discussions on Matrix and progress recorded on Github. 

You can see that in action here, as well as the close milestone for 0.1.0: https://github.com/glimpse-editor/Glimpse/milestones

> 2. get in touch with gimp devs
besides contributing upstream, glimpse devs should be in touch with gimp devs, make sure there's no same work that being work on both project. make some kind of unofficial agreement about the focus of the project, for example, gimp devs should be focusing on underlying technology, while glimpse devs should be studying and implementing best UI/UX for comfy and efficient workflow for the user

I have been following their IRC channel for some time now and over the past couple of weeks have started asking questions there. I also raised our first bug ticket with them to get questions answered yesterday. So I think it's fair to say that now we have a binary release we feel upstream are more likely to take us seriously :)

We don't have any agreements (official or not) about which areas both projects will cover, but I think what you described is how things will play out. GNU Image Manipulation Program will have bleeding-edge features, Glimpse Image Editor will be slightly behind but focus on usability.

> 3. forking form recent code of gimp, instead of stable release
if we base our project from stable release, our project will be obsolete soon, it's more work for glimse devs when major version of gimp is released. just imagine the pile of task to do when version 3 of gimp is released. it's using many different stuff, and it makes glimpse devs should redo many task that just won't work on new version. probably just base the project from master, or with many bleeding edge branches

We currently base from specific tagged releases (for example, Glimpse 0.1.x is built on a GNU Image Manipulation Program 2.10.12 base. Glimpse 0.2.x will be built on GNU Image Manipulation Program 2.10.14, etc).

We do not use upstream's master branch because the code is not always stable, and we would need to track all the changes they are making to the codebase in real time. We do not have the people or resources to do that, so it is better for us to work with "known stable" releases and "known good" dependency versions.

We do however keep an eye on upstream bugs that impact the versions we use and their current status. If they are already fixed then we know it is resolved when we catch up to their latest release. If it is not fixed then we can look into resolving that problem.
