### ISSUE TITLE
0.1.0 Won't Install on Windows

### ISSUE THREAD

**Issue by sandrockcstm** [glimpse-editor/Glimpse#253]
I'm attempting to install 0.1.0 on my W10 machine and I can't get past the "gathering information" portion of the loading bar.  The installation window just disappears and doesn't come back.  I've attempted this on both the signed and unsigned packages, and always click "yes" when asked for permission.

**Comment by TrechNex** [comment]
I would suggest making sure Glimpse is not already present in Add/Remove programs (if it, remove it), ensure Windows 10 is fully updated (use the tool available [at this link](https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant)), then restart your machine before trying again.

Usual reasons for an installer to hang at this stage are a) there was another installer running at the same time, b) Windows is not up-to-date and trying to install drivers or updates in the background, c) an anti-virus program is blocking it.

This also has the caveat that if you are using a computer issued to you by your employer rather than your own equipment, the IT systems administrator may have activated group policy settings that prevent you from installing third party software.

**Comment by sandrockcstm** [comment]
That did it, thank you!
