### ISSUE TITLE
Why are you promoting that GIMP name is offensive?

### ISSUE THREAD

**Issue by abitrolly** [glimpse-editor/Glimpse#345]
English is not my original language, and I've just learned from your FAQ that the GIMP is a f* word. I've never heard about this usage before. Why are you trying to offend GIMP users and contributors by saying that GIMP is not name of an image editor, but some bad joke from the old movie?

I wouldn't be concerned about this at all, but you're telling that you're advocating open source software in educational environment, and defaming GIMP there to get you more attention and funds looks very mean to me.

**Comment by TrechNex** [comment]
Because it's not defamatory, it's the truth. Those reasons were outlined in published interviews by the people that started the project back in the '90s and early '00s. Sometimes the truth makes people uncomfortable, but it's their choice if they want to accept it or bury their heads in the sand.

We have tried not mentioning this at all in the FAQs as you suggested, but as you will also see from the YouTube videos that were made about us last summer and the online comments we have received, it just leads to people not understanding why the word was offensive, assuming its use was totally unintentional, and accusing us of being "over-sensitive social justice warriors with a political agenda".

By being crystal clear about those things and explaining what the practical impact is, people can better understand why the fork was started in the first place. Our contributors also receive a lot less online abuse and harassment because people understand we're not trying to "replace" or "supplant" the GNU Image Manipulation Program, we're just offering an alternative option and both projects can peacefully co-exist.

Also, the GNU Image Manipulation Program's FAQs literally told us we should do this: https://www.gimp.org/docs/userfaq.html#i-dont-like-the-name-gimp-will-you-change-it

**Comment by TrechNex** [comment]
As for the attention we got, that was the choice of the people who made those videos, articles and podcasts. They knew that this one specific issue would get people hot under the collar and they made their advertising money from it. :)

With regards to our donations, we are completely transparent about how we use them. We don't get much (about $50 a month currently, which covers server costs), but each time we do a major release we pass some of that money back to the GNU Image Manipulation Program developers.

I also work directly with the GNU Image Manipulation Program developers on their IRC chat and Gitlab to chat about upcoming changes, bugs we've discovered/resolved and to ask questions when we get stuck.

Contrary to what you may have seen from people yelling at each other on social media, relations between the people actually doing the work are not bad. :)

**Comment by abitrolly** [comment]
@TrechNex your claim that the perception if GIMP name over 20 years did not change is not true. In fact, **you are changing the perception of the GIMP name** by referring to the 30 years old bad joke. You know that the official position of the project is that GIMP acronym stands for GNU Image Manipulation Program. Why are you insisting that everybody should refer to GIMP differently?

**Comment by TrechNex** [comment]
The people within our project disagree that expanding the acronym is a good enough solution, and we do not think that "sanitising the word" actually works in reality.

If you have realized that knowing the origin of the name changes peoples' perception of the GNU Image Manipulation Program, then you're actually agreeing with us that it's a problem.

Finally, no one is telling anyone what to do. You _can_ use the GNU Image Manipulation Program, and you _can_ use Glimpse Image Editor. There's room enough in the world for both programs to exist.

**Comment by abitrolly** [comment]
I don't agree with you that knowing the origin for the name **changes** peoples' perception of the GNU Image Manipulation Program. But you propaganda does affect new users in education environment, which I mentioned in the first post.

So the problem here is that you're claiming that all people out there have association with GIMP name with some dubious stuff in the past. But in fact, it is your agenda to insist on that, and go as far as claiming that just using it as is without any reference to the past is "sanitising the word". 

That's why I am asking - why are you doing this? What is your motivation?

**Comment by TrechNex** [comment]
Our motivation is to articulate the problems we seek to resolve. You will notice on that FAQs page we also talk about usability improvements, pre-bundling plug-ins, etc.

We are not a government with "propaganda" and we are not a company with "public relations". This project is just a group of free software and Linux users volunteering their free time to hack on some code, something we are permitted and encouraged to do by the GNU General Public License v3 and the FAQs page of the project we forked from.

The "evil plan" is to give disgruntled users of the GNU Image Manipulation Program another option, and to repackage the application in a way that appeals better to people who are not already using free software.

You will have noticed on store/app centre pages where we publish the app we focus on the practical improvements, and people only see the (correct) information you want us to conceal if they specifically seek it out as an answer to a question from our FAQs page.

I have also outlined in previous answers the things we do to co-operate with the upstream project from which we forked, to demonstrate that we are not "being mean" to them.
