### ISSUE TITLE
Glimpse does not show installed printer (whether connected or not)

### ISSUE THREAD

**Issue by robrill** [glimpse-editor/Glimpse#359]
Hi, 

When attempting to print from Glimpse to an HP Designjet 500, the print dialog does not show or provide an option to connect to the printer. ElementaryOS shows the printer installed and connected, GIMP shows the printer available in the print dialog whether the printer is connected or not, and successfully prints to it. 

Using: 

Glimpse 0.1.2 (installed from snapd) 
HPLIP 3.17.10
CUPS 2.2.7
elementaryOS 5.1.2 (ubuntu 18.04.3 based)

**Comment by TrechNex** [comment]
cc @hellsworth as I suspect the fix is just a case of adding permissions to access printers by default.

On Ubuntu Software Software you can normally do that in the app entry, but as you're using ElementaryOS you would need to do it through the terminal.

More info: https://ubuntu.com/blog/a-guide-to-snap-permissions-and-interfaces

**Comment by robrill** [comment]
@TrechNex thanks-- `snap connect glimpse-editor:cups-control` is a functional workaround

**Comment by hellsworth** [comment]
Yep, the cups-control isn't automatically connected so you need to manually connect it with
```
snap connect glimpse-editor:cups-control
```
