### ISSUE TITLE
The logo resembles Luminar too much

### ISSUE THREAD

**Issue by kofa73** [glimpse-editor/Glimpse#372]
### Describe the bug
The logo seems to be a knock-off of Luminar's.

### To Reproduce
1. Go to any site mentioning Glimpse
2. Check the logo in the article
3. Compare with Luminar's
4. See the similarity

### Expected behavior
An OSS project respects other projects' and companies' intellectual property rights.

**Comment by TrechNex** [comment]
For comparison: https://en.wikipedia.org/wiki/Luminar_%28software%29#/media/File:Luminar_2020.svg

The earliest use of the Luminar application logo described seems to be in 2018 (previously it was just a blue circle with an "L" in it).

cc @jaames the original artist to confirm or deny if they took any inspiration from this or not. My understanding is that it is not a "knock off", we just happen to have produced a similar but legally distinct idea.

In most countries logo concepts are not copyrightable, and the application icon linked to does not appear to be a registered trademark belonging to that company. In addition, our logo uses different colours, features, angles and details. You can see the latest version on our website also has a white border, and will be used with 0.1.4 onwards.

We have not received any complaints from that company, and there is no evidence that anyone has experienced "confusion" between our free software project and their proprietary software product. (In fact, we don't have a macOS port right now!)

I could also cite some examples of "prior art" debunk this, but I trust I've made my mind.

**Comment by jaames** [comment]
Hey there! I designed the logo for Glimpse. Here's a screenshot of my working file from when it was being developed:

<img width="733" alt="Screenshot 2020-04-03 at 20 11 03" src="https://user-images.githubusercontent.com/9112876/78396523-7475e500-75e7-11ea-8273-34999ef5174b.png">

If I remember correctly, after the first round of concepts the team liked the idea that represented a stack of lenses, and that gradually evolved into a multicolor stack of "layers" since that made more sense for an image editor. To finish it off I wrapped that in a cube/hexagon shape to help with the 3d effect.

So it wasn't intentionally a rip-off, we just ended up with a pretty similar concept. I definitely wasn't aware of Luminar at the time otherwise I would have steered things in a different direction. It does feel a bit awkward to learn that the logo is so similar to another image editor, perhaps we should consider maybe changing it with the UI rewrite or something?

**Comment by TrechNex** [comment]
Indeed. I think so long as we continue forking the GNU Image Manipulation Program we should stick to the same logo, as that's what people have associated it with.

For the parallel rewrite effort that @Member1221 is heading up, that would need to take on a new identity anyway so people understand it's not the same thing. That could potentially be spun out with a different name and logo.

**Comment by jaames** [comment]
Yeah, giving the rewrite a completely new identity is absolutely a good call. Unfortunately I don't know if Glimpse will ever be able to shake the public perception of it being a rebranded GNU IMP fork, and we wouldn't want the UI effort to be ignored because of that. :)

**Comment by kofa73** [comment]
Fair enough, sorry if I was too harsh.

**Comment by cristianovitorino** [comment]
> [...] Unfortunately I don't know if Glimpse will ever be able to shake the public perception of it being a rebranded GNU IMP fork, and we wouldn't want the UI effort to be ignored because of that. :)

That depends of how unique the UI Rewrite will turn out, how much attention we get along the way and how many years we endure innovating post-rewrite. Nobody goes around calling Ubuntu a Debian's ripoff anymore, or who in the earth aside from Unix/Unix-Like developers knows that macOS is Darwin OS under the hood, that by itself was forked from BSD + other projects.

Time will make our indentity very clear and unique.
