### ISSUE TITLE
Benefits of Glimpse over GIMP

### ISSUE THREAD

**Issue by TheEvilSkeleton** [glimpse-editor/Glimpse#380]
Just wondering, what are the **real** benefits of using Glimpse over GIMP? I used both GIMP and Glimpse and they both feel the same.

**Comment by awsyoos** [comment]
There's no other reasons than making GIMP less "offensive", even though no body complained about the name being offensive to the scale that we needed a rename.
This is just dumb.

**Comment by xgqt** [comment]
![image](https://user-images.githubusercontent.com/47485207/79076321-ab837f00-7ce8-11ea-9a17-ec08dca17bec.png)

**Comment by taminaru** [comment]
obviously the most offensive term to have ever been created is ''gimp''

**Comment by thidzz** [comment]
I'm waiting for some refactoring on GIMP interface. I used Photoshop and now Affinity for many years and I was update myself about gimp because of the open source community. The problem with gimp, in my opinion, was always about their counter-intuitive, terrible workflow of the software. I guess glimpse came to solve this interface problem (that was what I understood about their proposition), but they're not there yet, I guess.

**Comment by KojyGH** [comment]
LOL. They even ask to donate to basically stolen software.

**Comment by TheEvilSkeleton** [comment]
> I'm waiting for some refactoring on GIMP interface. I used Photoshop and now Affinity for many years and I was update myself about gimp because of the open source community. The problem with gimp, in my opinion, was always about their counter-intuitive, terrible workflow of the software. I guess glimpse came to solve this interface problem (that was what I understood about their proposition), but they're not there yet.

Same honestly, I expected them to port it to GTK3 but they haven't, so I really don't see any benefits of this so called "project".

**Comment by xgqt** [comment]
I'm scratching my head and thinking why didn't you (devs) go VSCodium route - where you do not fork the project but create a repo which overlays "ontop" of a existing software. Full fork in this case is... weird. Licensing issues?
Refs: https://github.com/VSCodium/vscodium

**Comment by TheMuurtje** [comment]
![changes](https://user-images.githubusercontent.com/27971295/79076529-25246880-7cfb-11ea-92b5-02d9fbc03eb5.png)

**Comment by KojyGH** [comment]
> 
> 
> > I'm waiting for some refactoring on GIMP interface. I used Photoshop and now Affinity for many years and I was update myself about gimp because of the open source community. The problem with gimp, in my opinion, was always about their counter-intuitive, terrible workflow of the software. I guess glimpse came to solve this interface problem (that was what I understood about their proposition), but they're not there yet.
> 
> Same honestly, I expected them to port it to GTK3 but they haven't, so I really don't see any benefits of this so called "project".

It doesn't even follow the Windows system theme, I have a nice dark custom theme for Windows 10 called "Penumbra 10". But guess what, with Glimpse you're stuck with a ugly Windows 95 theme if you apply the system theme, lol.

**Comment by awsyoos** [comment]
Honestly, if I had to twist whoever "created" "Glimpse" head and examine every single brain cell they have, I would still not find a single reason other than him/her wanting to boast about "forking" and "maintaining" a large project for attention, and the fact that their main intentions are to "fix" the name, EVEN THOUGH NO ONE COMPLAINED ABOUT THE NAME IN THE FIRST PLACE. Which is all in the end comes to my conclusion of them wanting more attention. It's either that whoever came up with this is an elaborate troll, or if they're genuinely thinking that what they're doing is good... then oh god I feel bad for them.

**Comment by KojyGH** [comment]
> 
> 
> Honestly, if I had to twist whoever "created" "Glimpse" head and examine every single brain cell they have, I would still not find a single reason other than him/her wanting to boast about "forking" and "maintaining" a large project for attention, and the fact that their main intentions are to "fix" the name, EVEN THOUGH NO ONE COMPLAINED ABOUT THE NAME IN THE FIRST PLACE. Which is all in the end comes to my conclusion of them wanting more attention. It's either that whoever came up with this is an elaborate troll, or if they're genuinely thinking that what they're doing is good... then oh god I feel bad for them.

I mean the only thing dope about this "project" is the icon. I wouldn't mind it using it to replace the regular GIMP icon.

**Comment by xgqt** [comment]
> > Honestly, if I had to twist whoever "created" "Glimpse" head and examine every single brain cell they have, I would still not find a single reason other than him/her wanting to boast about "forking" and "maintaining" a large project for attention, and the fact that their main intentions are to "fix" the name, EVEN THOUGH NO ONE COMPLAINED ABOUT THE NAME IN THE FIRST PLACE. Which is all in the end comes to my conclusion of them wanting more attention. It's either that whoever came up with this is an elaborate troll, or if they're genuinely thinking that what they're doing is good... then oh god I feel bad for them.
> 
> I mean the only thing dope about this "project" is the icon. I wouldn't mind it using it to replace the regular GIMP icon.

The you can just use a custom theme :D

**Comment by TrechNex** [comment]
I suggest reading our FAQs page: https://glimpse-editor.org/about/

This software is not "stolen". The GNU Image Manipulation Program is free software licensed under the GNU GPLv3, and Glimpse Image Editor is a derivative work licensed under the same terms. :man_facepalming: 

So, let's take this from the top...

The GNU Image Manipulation Program is a huge 25 year old code base that is highly modular, contains tens of millions of lines of code, and the building and packaging process does not have particularly good documentation.

An example of how long it can take to make just a simple change was when we wanted to rename "Gimpressionist" to "Impressionist". We had to change 149 different files by hand to make that happen!

As an FYI we also wrote our own Windows installer from scratch, because the upstream one wasn't documented at all. Our installer runs faster because we use WiX instead of InnoSetup, and we only take up 500MB on the system (instead of 3.5GB) because we didn't just bundle an entire installation of MinGW with it. Upstream have been briefed on what we did, and they seemed very interested.

If you want to see other work we did on building and packaging then just take a look inside the `build-aux` folder and our `HACKING` file. Then compare it to the upstream code we forked from: https://github.com/GNOME/gimp/tree/GIMP_2_10_12

And this is not to mention the many hours we put in to modifying the code so it can be installed and run at the same time as the GNU Image Manipulation Program, updating the credits so there's a clear delineation between the upstream and downstream contributors, backporting changes from 2.10.18, supporting Jenkins/Travis-CI, modifying the icon packs, updating hundreds of translations, and all the other changes in the `NEWS` file. We also did all of that in a way that doesn't break the underlying API third party plug-ins use or the commit hashes from upstream.

Then of course there's all the things we've done to actually build a free software project around it and market this application as something other people would actually want to use. That's meant websites, social media profiles, Matrix channels, wikis, and a whole host of other systems that we don't just have to maintain and self-host, but also protect from your relentless trolling.

This project is developed by me (http://trechnex.freeshell.org/) and half a dozen GNOME contributors. We have tens of thousands of downloads, $50 a month on donations, Matrix channels with lots of activity on them & a direct line to the upstream contributors to ask questions/resolve issues.

So sure, if you want to go around insisting we've done very little you're welcome to do so, as I'm sure that serves your political agenda. But I hope you're aware that people aren't stupid, and when they see that what you're saying doesn't actually match up with the reality, we are not the ones that end up looking silly. :)

**Comment by TrechNex** [comment]
Marking as duplicate of #35 and #116

**Comment by TheEvilSkeleton** [comment]
> I suggest reading our FAQs page: https://glimpse-editor.org/about/
> 
> This software is not "stolen". The GNU Image Manipulation Program is free software licensed under the GNU GPLv3, and Glimpse Image Editor is a derivative work licensed under the same terms. man_facepalming
> 
> So, let's take this from the top...
> 
> The GNU Image Manipulation Program is a huge 25 year old code base that is highly modular, contains tens of millions of lines of code, and the building and packaging process does not have particularly good documentation.
> 
> An example of how long it can take to make just a simple change was when we wanted to rename "Gimpressionist" to "Impressionist". We had to change 149 different files by hand to make that happen!
> 
> As an FYI we also wrote our own Windows installer from scratch, because the upstream one wasn't documented at all. Our installer runs faster because we use WiX instead of InnoSetup, and we only take up 500MB on the system (instead of 3.5GB) because we didn't just bundle an entire installation of MinGW with it. Upstream have been briefed on what we did, and they seemed very interested.
> 
> If you want to see other work we did on building and packaging then just take a look inside the `build-aux` folder and our `HACKING` file. Then compare it to the upstream code we forked from: https://github.com/GNOME/gimp/tree/GIMP_2_10_12
> 
> And this is not to mention the many hours we put in to modifying the code so it can be installed and run at the same time as the GNU Image Manipulation Program, updating the credits so there's a clear delineation between the upstream and downstream contributors, backporting changes from 2.10.18, supporting Jenkins/Travis-CI, modifying the icon packs, updating hundreds of translations, and all the other changes in the `NEWS` file. We also did all of that in a way that doesn't break the underlying API third party plug-ins use or the commit hashes from upstream.
> 
> Then of course there's all the things we've done to actually build a free software project around it and market this application as something other people would actually want to use. That's meant websites, social media profiles, Matrix channels, wikis, and a whole host of other systems that we don't just have to maintain and self-host, but also protect from your relentless trolling.
> 
> This project is developed by me (http://trechnex.freeshell.org/) and half a dozen GNOME contributors. We have tens of thousands of downloads, $50 a month on donations, Matrix channels with lots of activity on them & a direct line to the upstream contributors to ask questions/resolve issues.
> 
> So sure, if you want to go around insisting we've done very little you're welcome to do so, as I'm sure that serves your political agenda. But I hope you're aware that people aren't stupid, and when they see that what you're saying doesn't actually match up with the reality, we are not the ones that end up looking silly. :)

@TrechNex Impressive, thank you for the information. 

> Then of course there's all the things we've done to actually build a free software project around it and market this application as something other people would actually want to use. That's meant websites, social media profiles, Matrix channels, wikis, and a whole host of other systems that we don't just have to maintain and self-host, but also protect from your relentless trolling.

I mean, just because others were trolling, it doesn't mean I was, sure a lot of them were my friends, but I never asked them to comment; I just wanted the upvotes and I apologise for this because it was my fault too. I was asking a legitimate question because it does not say much about what you guys have done, and the UI looks exactly the same as GIMP. But I do admit that the project did seem very silly due to some people being really offended with the name. I can now say that I do like the project because GNU in general are shit when it comes to documentation, and even if I love GIMP, I cannot disagree that it sucks because all the settings are a mess. 

Also, just want to say, this is free and open source, so just do whatever you want because you have the freedom. I do not see the point of trolling in free open source projects because it is all I support technologically speaking. Sorry for making it look like it was all a troll.

**Comment by resynth1943** [comment]
Nice. Thank you for the clarification @TrechNex.

**Comment by Member1221** [comment]
I am going to lock this issue to prevent more trolls piling on. @TrechNex can unlock if he feels like it.
