### ISSUE TITLE
Reporting potential security related issues

### ISSUE THREAD

**Issue by lesserwhirls** [glimpse-editor/Glimpse#401]
Is there a preferred way to inquire about / report potential security related issues?

**Comment by TrechNex** [comment]
It depends on the nature of the enquiry.

If it's to tell us that a Windows anti-virus program is flagging Glimpse Image Editor as a virus, that's cold case. We inherited a complicated dynamically-linked application from upstream, and they tend to fair better than we do because they have a bigger userbase complaining to AV companies about the false positive.

If it's a code-level exploit that's common between Glimpse Image Editor and the GNU Image Manipulation Program, then the GNU Image Manipulation Program developers are the better people to disclose it to because they have the capacity to turn around a more effective fix faster (and we would subsequently backport it)

If it's an exploit that's specific to Glimpse Image Editor, you can either raise it as an issue here or (if it's particularly severe) you can send a private encrypted message to a member of our governance team on Matrix using the links here: https://glimpse-editor.org/code-of-conduct/

**Comment by lesserwhirls** [comment]
Awesome, thank you! In this case, it is an antivirus warning, but it's triggering on what looks to be two third-party dependencies and not the core Glimpse (or GNU Image Manipulation Program). Likely a false positive, but I always try to hunt down where the executable are coming from just to be sure. I was having trouble figuring out the specific dependency, but I believe I have it figured out now. I'll go ahead and close this out. Thank you once again!
