### ISSUE TITLE
Replace Wilber with a different icon / mascot

### ISSUE THREAD

**Issue by chaomodus** [glimpse-editor/Glimpse#47]
There are numerous versions of Wilber in data/images, including I believe the one that is the background for the empty frame and ones that are used for icons (in particular gimp-logo.png, wilber.png, wilber-icon.png and wilber-ui-shadow.svg). There are also some of them that don't seem to be used for anything but I haven' searched extensively (gimp-devel-logo.png, wilber-devel*, wilber-tips.png and wilber-wizard.png). 

It'd be nice to replace these with a mixture of Glimps's mascot and icons (whatever those end up being).

**Comment by Member1221** [comment]
Yup, that's what we intend to do once we have a mascot :)

**Comment by ChameleonScales** [comment]
I don't really like Wilber's face design with his perfectly circular eyes of different size, shiny spherical nose and uninterrupted ears curve. He kinda looks like a character on a cheap cereal box. But at the same time I love the concept of a furry, undefined dog-like animal with a brush in its mouth and wearing an artzy hat (at some point in the past: ![](https://chameleonscales.owncube.com/index.php/core/preview?fileId=2269&x=1920&y=938&a=true))
Since you haven't completely changed the name (**G**L**IMP**SE), how do you feel about keeping some aspects of the mascot?

**Comment by BrainBlasted** [comment]
Glimpse is just "Glimpse", not GLIMPSE :)  I think we'd rather forge our own identity, but maybe there could be some abstract similarities in future iconography. I personally would like to try something new/without a mascot.

**Comment by ChameleonScales** [comment]
My bad, I thought the name was still a hint to the original to not drift away too far while getting rid of the slur issue.
Anyway, ok then, I like animal mascots for foss programs, I find it a little more welcoming and less corporate-ish but I understand that some people may find it childish or something. I may be a big child in disguise 🧒.

**Comment by BrainBlasted** [comment]
Feel free to propose one while we figure this out :)

**Comment by measlytwerp** [comment]
This is a concept I've been playing with since the project was announced... but never felt comfortable with. I thought something modern with bold colours would suit best, I'm not much of a fan of mascots.

![glimpse](https://user-images.githubusercontent.com/42093217/63632047-a3e66b80-c66e-11e9-8aea-7079e8bfdbbf.png)

**Comment by measlytwerp** [comment]
A black and white version:

![image](https://user-images.githubusercontent.com/42093217/63633221-c9ca3b00-c683-11e9-886d-5ffc6260fb68.png)

**Comment by measlytwerp** [comment]
The SVG for anyone to play with...

[Logo.zip](https://github.com/glimpse-editor/Glimpse/files/3537027/Logo.zip)

**Comment by ChameleonScales** [comment]
it looks pretty good but personally I think an eye icon makes it  look too much like an image viewer. If the name is already hinting at that, making the icon follow may confuse some people.

**Comment by stuaxo** [comment]
It's a shame not to have a mascot any more, makes things feel a little bland.

**Comment by Member1221** [comment]
The plan is to have our own mascot at some point

**Comment by TrechNex** [comment]
Moved to 0.x soft fork candidate. I think removing Wilber from every part of the UI for 0.1 is not realistic because of how embedded it is into the underlying code & throughout the UI. 

I think it would be better to phase Wilber out as part of a gradual process over the course of several 0.x releases. In each case it can either be replaced with a generic icon or our logo.

**Comment by TrechNex** [comment]
Moving to 0.1.0 milestone and counting as fixed. While we haven't fully extracted Wilber imagery from the codebase, I think it's fine to use as a fallback. (The legacy icon theme for example using the Wilber logo makes it clear that you are using icons from upstream and therefore may expect to see more of that character)

If we catch any more instances of Wilber popping up in the UI we can raise them as individual bugs to fix.

**Comment by creepertron95** [comment]
@Member1221 I know this issue is closed, but speaking of mascots, there is this guy, Tyson Tan that designed mascots for open source products, free of charge.

https://tysontan.com/mascots/
https://twitter.com/TysonTanX
https://www.deviantart.com/tysontan
