### ISSUE TITLE
Will be the AVIF format supported by Glimpse?

### ISSUE THREAD

**Issue by novomesk** [glimpse-editor/Glimpse#499]
Hello,
I am a fan of AVIF format and I am just curious whether it will be supported by Glimpse project too.

The support could be added by extending the [file-heif.c](https://github.com/glimpse-editor/Glimpse/blob/dev-g210/plug-ins/common/file-heif.c) plugin similar way like it was done in
https://gitlab.gnome.org/GNOME/gimp/-/blob/gimp-2-10/plug-ins/common/file-heif.c

**Comment by TrechNex** [comment]
We will be rebasing to a new GNU Image Manipulation Program release for Glimpse Image Editor 0.3.0 (due in July 2021).

At that point we will inherit all the changes that have been made since 2.10.18, the version we are currently based on. We will only be back porting bug-fixes and security updates in Glimpse Image Editor 0.2.2 (due in January 2021)

**Comment by novomesk** [comment]
ok, thanks for clarification.
