### ISSUE TITLE
Сan't open files .jpg, .png

### ISSUE THREAD

**Issue by JackJeisly** [glimpse-editor/Glimpse#512]
### Brief Summary
Can't open files .jpg, .png

### More Details
Why I can't open files .jpg, .png, etc? Or to import these files, I don't see this option in menu? I use Glimpse Image Editor-22.git-1fa4228-x86_64.AppImage in OS Debian 9.
Thank you.

**Comment by TrechNex** [comment]
Sounds like this might be related to #510. 

Have you tried downloading the latest AppImage? The commit hash in the file title doesn't match the latest one.

Unlike our other releases, the AppImage isn't a "tagged" version, it follows the tip of our development branch.

**Comment by JackJeisly** [comment]
Thank you for fast reply!
I get this Appimage by link https://github.com/glimpse-editor/Glimpse/releases/tag/continuous and it marked as last.
I install a snap-version, in there all right for file formats that can be open. 
But one moment yet. I have some "logical" disks with mount points that placed out off "standart" folders as "root", "home" etc. As sample, disks with mount points as /MyMedia, /Info... And when I open file a program see them in folder list, but write "can't mount".

**Comment by TrechNex** [comment]
Okay. The other thing I was going to point out is that the AppImage is built on a Ubuntu 20.04 LTS host, so it's likely that Debian 9 (which stopped receiving new feature updates in July 2020) might be missing required dependencies at the correct versions.

You can see the EOL dates for Debian here: https://wiki.debian.org/DebianReleases

As for the Snap, that is a "sandboxed" format. This means that it only has limited access to the underlying system. You can change permissions to a limited extent in the Snap Store application (eg. enable "removable media" so that devices under `/mnt` or `/media` are accessible).

**Comment by JackJeisly** [comment]
I know that actual release now "Buster", of course. But peoples use "Stretch" and "Stretch" based Devuan too. No pretensies. You make good and user-friendly software, and I think that it must work in oldstable too, which many peoples are use for old computers.
Thank you!
