### ISSUE TITLE
Add package to Scoop

### ISSUE THREAD

**Issue by BenLubar** [glimpse-editor/Glimpse#65]
Examples:

https://github.com/lukesampson/scoop-extras/blob/master/bucket/gimp.json
https://github.com/lukesampson/scoop-extras/blob/master/bucket/krita.json

**Comment by TrechNex** [comment]
We could also investigate chocolatey: https://chocolatey.org/
The "Windows Store" may also be worth a look as a distribution platform.

**Comment by TrechNex** [comment]
I think that realistically scoop & chocolatey would probably be "unsupported" distribution platforms, where we rely on the wider community making the manifests for us because only a limited number of highly technical people are using those distribution mechanisms.

Much like other "unsupported" channels though we are happy to answer questions and possibly apply patches if needed. (For reference, unlike GNU Image Manipulation Program we will be distributing an MSI installer and not an EXE file or ZIP)

I'm tracking the idea of publishing to the Windows Store on #180

**Comment by katktv** [comment]
I def vouch for it as the active scoop user. Really helps when it comes to managing software on Windows, and it def is used by plenty of ppl.

**Comment by TrechNex** [comment]
Just commenting to confirm that we haven't forgotten about this! After 0.2.0 is released in July, this is something I'm going to be looking at. The reason I held off is because we'll have a new 64-bit installer and ZIP files, so would have more flexibility about how scoop installs/deploys the end result.

**Comment by corbob** [comment]
> 
> 
> We could also investigate chocolatey: https://chocolatey.org/
> The "Windows Store" may also be worth a look as a distribution platform.

@TrechNex FWIW: I created the choco package, and am currently updating it to 0.2.0 release. Let me know if you'd like to take over management of the package at any point and we can get it sorted out.

**Comment by TrechNex** [comment]
@corbob if you can provide a link to it I'll update the downloads page to point to it as a "Community-Supported Source" 👍 

We could pick it up in future, but it'll depend on how many people are using it and if we can get one of our contributors to maintain it. Currently I'm solely responsible for our Windows port, so I have no issues leaving with someone more knowledgeable about the subject.

**Comment by moracabanas** [comment]
> I think that realistically scoop & chocolatey would probably be "unsupported" distribution platforms, where we rely on the wider community making the manifests for us because only a limited number of highly technical people are using those distribution mechanisms.
> 
> Much like other "unsupported" channels though we are happy to answer questions and possibly apply patches if needed. (For reference, unlike GNU Image Manipulation Program we will be distributing an MSI installer and not an EXE file or ZIP)
> 
> I'm tracking the idea of publishing to the Windows Store on #180

Some manifests just wget the MSI then unpack and install it so you can have a easy list whats installed on your PC and you can build your dev toolset easily on new computers as you install that list like a "requirements.txt". Then if you mess with any package just remove ~/scoop/apps/<package> or run "repair". I love it

**Comment by TrechNex** [comment]
@corbob I've added a link to your Chocolatey entry on our downloads page.

@moracabanas thank you for the Scoop tips. If you have any doc links that would be really helpful 👍

**Comment by moracabanas** [comment]
Sure! There is the Scoop docs to create an app manifest
[app mannifest docs](https://scoop-docs.now.sh/docs/concepts/Creating-an-app-manifest.html#a-basic-example)

I've never made any app manifesst but it doesn't seem hard

**Comment by TrechNex** [comment]
Okay, I'm going to have a crack at doing this some time in the next week or two. In the meantime, the wider community has actually added Glimpse 0.2.0 to WinGet and Chocolatey, which is very cool. I've added to links to our website's downloads page.

**Comment by TrechNex** [comment]
I had a crack at this today, and fell at the first hurdle because I wasn't able to install Scoop on a standard Windows 10 Home installation. There are missing components, and a mainstream anti-virus program (McAfee) blocked it.

I will try again later on this week on a Windows 10 Pro installation. If that does not work then we will need the assistance of someone that actually uses Scoop. If they can get a working JSON file up and running, we will host it from our website.

**Comment by moracabanas** [comment]
> I had a crack at this today, and fell at the first hurdle because I wasn't able to install Scoop on a standard Windows 10 Home installation. There are missing components, and a mainstream anti-virus program (McAfee) blocked it.
> 
> I will try again in the coming week on a Windows 10 Pro installation. If that does not work then we will need the assistance of someone that actually uses Scoop. If they can get a working JSON file up and running, we will host it from our website.

I have Windows 10 home and I successfully instaled scoop. I use windows defender and that give me no issues at all. You can try this things:
- temporary disable antivirus during scoop installation as it probably blocks Admin Powershell scripting with some Set-ExecutionPolicy.

- Then open Powershell as ADMIN and type `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`

- Next install scoop with `iwr -useb get.scoop.sh | iex`

It is so reliable at my setup with windows defender antivirus I just love it to manage my developer tools installation. 

I will try to help you as much as I can

(I recommend to add ~/scoop folder to any antivirus exceptions rule as it improves performance a lot. Software is installed there at level user so it is no risky to do that change)

**Comment by moracabanas** [comment]
I also found there are issues with Powershell 5 and antivirus, and the issue is gone with Powershell 7

https://github.com/lukesampson/scoop/issues/3966

**Comment by TrechNex** [comment]
I am concerned having gone through this folder that I've so far not seen any examples of Scoop installing or upgrading MSI installers: https://github.com/lukesampson/scoop-extras/tree/master/bucket

If someone knows of a tool that is installed using an MSI instead of ZIP, 7Z or EXE then I can probably use that a starting point.

Otherwise to make scoop work I'm going to have to look at essentially writing a custom installer specifically for scoop, which would make this a much bigger job.

**Comment by TrechNex** [comment]
@moracabanas @BenLubar could you try out this JSON file locally?
https://github.com/TrechNex/scoop-extras/blob/master/bucket/glimpse-editor.json

Instructions for testing: https://scoop-docs.now.sh/docs/concepts/Creating-an-app-manifest.html#a-basic-example

If that works then I will raise a pull request so it'll appear in the scoop extras repository. (I am unable to get scoop working on my own machine, so if changes are needed I hope this is at least a good starting point)

**Comment by TrechNex** [comment]
Linking to lukesampson/scoop-extras#4842
cc @bb010g

If that's the change that gets this merged, we will close the issue as fixed and link to Scoop.

**Comment by bb010g** [comment]
Sorry, missed this earlier. lukesampson/scoop-extras#4842 has been tested on my Windows machine, and should work just as well as other Scoop apps.
