### ISSUE TITLE
Please re-name the project to 'GIMP'

### ISSUE THREAD

**Issue by jonathancast** [glimpse-editor/Glimpse#96]
Gimp was a great name! It's a bit of playful fun, showing the project doesn't take itself too seriously.

Changing the name gives the opposite connotation. It implies you take yourself _way_ too seriously, and suggests you're defensive, bureaucratic, and overly concerned with your own image.

Free software does _not_ need to be "professional". Implying it does casts a negative light on anyone who wants to enjoy themselves while writing software.

Please reconsider this decision.

**Comment by TrechNex** [comment]
It's a good thing there isn't another project called that. Otherwise it would be awkward...

(We normally delete these "rib tickler" issues, but as we're probably going to get slammed with people doing this to mess with us we're going to leave it up so people can at least see it's not original and we're rolling our eyes at them)

**Comment by CondensedBrain** [comment]
You might be surprised to learn there's already a project called GIMP! They even advise people to fork it if they don't like the name.

**Comment by Member1221** [comment]
Marking this as wontfix to organize the issues.
