### ISSUE TITLE
Add support for snap packages 

### ISSUE THREAD

**Issue by EndrII** [glimpse-editor/Glimpse#99]
Please add your application to the [snap store](https://snapcraft.io/store)

**Comment by TrechNex** [comment]
We have so far established that Glimpse 0.1 will be a Flatpak and an AppImage on Linux. Whether 0.1 is also packaged as a Snap or this functionality is deferred to a later release depends on how involved that would be.

It was de-prioritized initially because Ubuntu users can still install Flatpaks and run AppImages. Canonical has a habit of killing off its own technology periodically!

**Comment by psymole** [comment]
Hi I just created a rudimentary Snap package of the current dev branch. still iterating on the snapcraft yaml to optimize some things but it builds and works. Here is the project if someones one to look or colaborrate on it. [https://github.com/psymole/Glimpse](https://github.com/psymole/Glimpse)

**Comment by TrechNex** [comment]
@psymole can you raise that as a pull request? It would help us review what you've changed much more easily and allow people to make suggestions inline with the code :)

**Comment by TrechNex** [comment]
Linking to #153

**Comment by TrechNex** [comment]
Moved to 0.1 milestone because a PR is actively being worked on for this.

**Comment by TrechNex** [comment]
To update there is now some basic support. Leaving open in anticipation of @hellsworth opening another PR as part of publishing to snapcraft process.

**Comment by TrechNex** [comment]
Confirming that we don't directly support Snap packages, but we accepted changes to facilitate third party support of Snaps.

Closing as changes are now applied :)
